name: Switch Nightly Build

on:
  push:
    paths:
      - Makefile_switch
      - source/scratch/**
      - source/sdl/**
      - gfx/**
      - include/**
      - .github/workflows/nightly-switch.yml
      - Dockerfile.switch
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.switch
          target: exporter
          outputs: type=local,dest=.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scratch NX Nightly
          path: scratch-nx.nro
