name: Wii U Nightly Build

on:
  push:
    paths:
      - Makefile_wiiu
      - source/scratch/**
      - source/sdl/**
      - gfx/wiiu/**
      - include/**
      - .github/workflows/nightly-wiiu.yml
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install RomFS
        run: |
          git clone https://github.com/yawut/libromfs-wiiu.git
          cd libromfs-wiiu
          make
          sudo -E make install
      - name: Build
        run: make PLATFORM=wiiu all package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Wii U Nightly
          path: build/wiiu/scratch-wiiu/
