name: Wii U Nightly Build

on:
  push:
    paths:
      - Makefile_wiiu
      - source/scratch/**
      - source/sdl/**
      - gfx/wiiu/**
      - include/**
      - .github/workflows/nightly-wiiu.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Modified Curl Package
        run: |
          git clone https://github.com/gradylink/wut-packages
          cd wut-packages/curl
          makepkg -si
      - name: Install Mist++
        run: |
          wget https://github.com/gradylink/mistpp-packages/releases/download/0.2.0-1/wiiu-libmistpp-0.2.0-1-any.pkg.tar.zst
          sudo dkp-pacman -U wiiu-libmistpp-0.2.0-1-any.pkg.tar.zst
      - name: Install libromfs-wiiu
        run: |
          git clone https://github.com/yawut/libromfs-wiiu.git
          cd libromfs-wiiu
          make
          sudo -E make install
      - name: Build
        run: |
          mkdir romfs
          make PLATFORM=wiiu all package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scratch Wii U Nightly
          path: build/wiiu/scratch-wiiu/
